spring:
  application:
    name: tregistry


server:
  port: 8484


logging:
  level:
    root: error
    cn.tannn.tregistry: debug


tregistry:
  server-list:
    - http://127.0.0.1:8484
    - http://127.0.0.1:8485
    - http://127.0.0.1:8486
